#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop aesdsocket daemon
# Description:       Controls the aesdsocket daemon
### END INIT INFO

DAEMON_PATH="/path/to/aesdsocket"
DAEMON_NAME="aesdsocket"
DAEMON_OPTS="-d"
PIDFILE="/var/run/$DAEMON_NAME.pid"

case "$1" in
    start)
        echo "Starting $DAEMON_NAME..."
        start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON_PATH -- $DAEMON_OPTS
        ;;
    stop)
        echo "Stopping $DAEMON_NAME..."
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        ;;
    restart)
        echo "Restarting $DAEMON_NAME..."
        $0 stop
        $0 start
        ;;
    status)
        if [ -e $PIDFILE ]; then
            echo "$DAEMON_NAME is running with PID $(cat $PIDFILE)"
        else
            echo "$DAEMON_NAME is not running"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0